### (done) 1. GET Users
GET http://localhost:8080/users

### 2. GET Users by Id
GET http://localhost:8080/users/2

### 3. Create a new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": 4,
  "name": "user4"
}

### 4. Update a user with specific Id
PUT http://localhost:8080/users/2
Content-Type: application/json

{
  "name": "new user2"
}

### 5. Delete user specific Id
DELETE http://localhost:8080/users/2